[package]
name = "my_service_api_grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.10"
prost = "0.12"
anyhow = { workspace = true }
tokio = { workspace = true }
my_service_domain = { workspace = true }

[build-dependencies]
tonic-build = "0.10"
